#!/usr/bin/env bash
# Check if all parameters have been provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
file="$1"
ip="$2"
username="$3"
key="$4"

# Transfer file
scp -o StrictHostKeyChecking=no -i "$key" "$file" "$username@$ip:~/"

#check if successful
if [ $? -ne 0 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
