#!/usr/bin/env bash
# Install nginx web server
# first, update package list to ensure we have latest version
sudo apt-get update -y
# Second , install Nginx
sudo apt-get install -y nginx
# Now start the nginx server
sudo service nginx start
# Create a default config to serve "Hello World" on port 80
#give permissions
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
# Restart nginx to apply changes
sudo service nginx restart
