#!/usr/bin/env bash
# Install nginx web server
# first, update package list to ensure we have latest version
sudo apt-get update -y
# Second , install Nginx
sudo apt-get install -y nginx
# Now start the nginx server
sudo service nginx start
# Create a default config to serve "Hello World" on port 80
#give permissions
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
# Redirect
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Not found page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
# Restart nginx to apply changes
sudo service nginx restart
