#!/usr/bin/env bash
#Update the package list and install HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend evanssese.tech
    timeout client  30000
    bind 0:80
    default_backend evanssese.tech_backend

backend evanssese.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 277128-web-01 54.87.250.91:80 check
    server 277128-web-02 3.89.160.129:80 check
EOT

sudo service haproxy restart
