#!/usr/bin/env bash
# backup my databases

# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
backup_file_name="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$backup_file_name" backup.sql
