#!/usr/bin/env bash
# This script displays lines containing the word "bash" to get the PID of your Bash process.
# shellcheck disable=SC2009
# Use ps command to find the lines containing the word "bash" in the process list
ps aux | grep bash | grep -v grep
