#!/usr/bin/env bash

# This script stops the 4-to_infinity_and_beyond process using pkill.

# Check if the process is running using pgrep
if pkill -0 "4-to_infinity_and_beyond" &>/dev/null; then
    # Send SIGTERM signal to stop the process using pkill
    pkill "4-to_infinity_and_beyond"
    echo "4-to_infinity_and_beyond process has been stopped."
else
    echo "4-to_infinity_and_beyond process is not running."
fi
