#!/usr/bin/env bash

# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the process using pgrep
pid=$(pgrep -o "4-to_infinity_and_beyond")

# Check if the process exists
if [[ -n $pid ]]; then
    # Send SIGTERM signal to stop the process
    pkill "4-to_infinity_and_beyond"
fi
