#!/usr/bin/env bash
# Port forward 8080 to 80
sudo vi /etc/ufw/before.rules
# Port forwarding from 8080 to 80
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
sudo ufw reload
